### ISSUE TITLE
Access profiles reset after turn on/off

### ISSUE THREAD

**Issue by Huber1** [AaronDavidSchneider/fritzprofiles#3]
If you switch an access profile to on or off, it resets the configuration for that profile.
In my case, it disables the blacklist check and the guest wifi check.
The "gesperrte Netzwerkanwendungen" Tab is not affected.

**Comment by AaronDavidSchneider** [comment]
originally asked in https://github.com/mammuth/ha-fritzbox-tools/issues/168#issuecomment-866857447
